CREATE TABLE LOGININFO (USERNAME varchar(255), PASSWORD varchar(255))
INSERT INTO LOGININFO VALUES ('admin', 'admin')
SELECT * FROM LOGININFO 

CREATE TABLE data (USERNAME varchar(255), PASSWORD varchar(255))
insert into data values ('admin', 'admin')

SELECT * FROM SYS.SYSTABLES WHERE TABLETYPE = 'T'

DROP TABLE USERANDPASSHASH


CREATE TABLE SESSIONS (EST_DURATION INT, INTENSITY INT, DESCRIPTION varchar(500), TYPE varchar(25), CREATOR varchar(255))
DROP TABLE SESSIONS
SELECT * FROM SESSIONS